name: notify

on:
  workflow_call:
    inputs:
      build_name:
        description: "Name of the build for notifications (e.g. 'The Linux build')"
        required: true
        type: string
      build_result:
        description: "Result of the build job ('success', 'failure', etc.)"
        required: true
        type: string
    secrets:
      DISCORD_WEBHOOK:
        required: true

jobs:
  notify:
    name: Exult-CI (IRC & Discord notification)
    runs-on: ubuntu-latest
    continue-on-error: true
    if: ${{ github.repository_owner == 'exult' && github.event_name != 'pull_request' }}
    steps:
      - name: IRC success notification (ircs://irc.libera.chat:6697/#exult)
        uses: mauke/notify-irc@v1
        continue-on-error: true
        if: inputs.build_result == 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          join: true
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ inputs.build_name }} \x033succeeded\x03."
      - name: IRC failure notification (ircs://irc.libera.chat:6697/#exult)
        uses: mauke/notify-irc@v1
        continue-on-error: true
        if: inputs.build_result != 'success'
        with:
          server: irc.libera.chat
          port: 6697
          channel: "#exult"
          nickname: github-actions
          join: true
          tls: true
          message: "\x0313exult\x03/\x0306${{ github.ref }}\x03 \x0314${{ github.sha }}\x03 https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }} ${{ inputs.build_name }} \x034failed\x03."
      - name: Discord success notification
        uses: opp-studio/discord-webhook-notify@2.2.5
        continue-on-error: true
        if: inputs.build_result == 'success'
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: Exult github-actions
          avatarUrl: https://avatars.githubusercontent.com/u/15114538?s=200&v=4
          text: '**[${{ inputs.build_name }} succeeded:](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**'
      - name: Discord failure notification
        uses: opp-studio/discord-webhook-notify@2.2.5
        continue-on-error: true
        if: inputs.build_result != 'success'
        with:
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          username: Exult github-actions
          avatarUrl: https://avatars.githubusercontent.com/u/15114538?s=200&v=4
          text: '**[${{ inputs.build_name }} failed:](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})**'
